### ISSUE TITLE
Javascript error when running app

### ISSUE THREAD

**Issue by heycameron** [gabrieljmj/phunky#2]
<img width="422" alt="capture" src="https://cloud.githubusercontent.com/assets/961746/17458725/ba13bf36-5bd0-11e6-9b35-8b60610ce64e.PNG">
After installing electron (I even restarted) I get this error attempting to run `npm start` same with `$ electron app/main.js`

Any ideas on how to get around this?

**Comment by gabrieljmj** [comment]
That's a problem with electron version. At `v0.4` there was a package called `app` for electron app. Now (`v1.3`), `app` is on electron module.

**I will update the electron version.**

If you want to test, go to `app/main.js`

``` js
const app = require('electron').app
```

instead of `require('app')`

and in `app/phunky-window.js`:

``` js
const BrowserWindow = require('electron').BrowserWindow 
```

and `win.loadUrl` to `win.loadURL`.

**Edit**
Done! [9ff6523cf2e9e63f38ac15531199002753ba66f3](https://github.com/gabrieljmj/phunky/commit/9ff6523cf2e9e63f38ac15531199002753ba66f3)
